# Generated by Django 4.0.5 on 2022-07-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='articles_mini_text',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='caption_text',
        ),
        migrations.AddField(
            model_name='articles',
            name='caption_mini_text',
            field=models.CharField(default='kek', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='caption_name',
            field=models.CharField(default='kek', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='articles_text',
            field=models.TextField(max_length=2000),
        ),
    ]
