# Generated by Django 4.0.5 on 2022-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_coments_remove_articles_articles_mini_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='caption_img',
            field=models.TextField(default='kek'),
            preserve_default=False,
        ),
    ]
