# Generated by Django 4.0.5 on 2022-07-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comments_delete_coments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name_article',
            new_name='articles',
        ),
    ]
