# Generated by Django 4.0.5 on 2022-07-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_name_article_comments_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='count_comm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
