# Generated by Django 4.0.5 on 2022-07-09 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articles_count_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
