# Generated by Django 4.0.5 on 2022-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='caption_img',
        ),
        migrations.AddField(
            model_name='articles',
            name='rank_articles',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Histtory', 'Histtory'), ('Facts', 'Facts'), ('Guide', 'Guide')], default='Blog', max_length=10),
        ),
    ]
