# Generated by Django 4.0.5 on 2022-07-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_articles_caption_img_articles_rank_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='rank_articles',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Histtory', 'History'), ('Facts', 'Facts'), ('Guide', 'Guide')], default='Blog', max_length=10),
        ),
    ]
