# Generated by Django 4.0.5 on 2022-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_articles_count_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_image',
            field=models.ImageField(default='0', upload_to='static/articles'),
            preserve_default=False,
        ),
    ]
