# Generated by Django 4.0.5 on 2022-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_articles_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
