# Generated by Django 4.0.5 on 2022-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_articles_pub_date_alter_comments_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.TextField(default='#'),
        ),
    ]
