# Generated by Django 4.0.5 on 2022-07-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_articles_article_image_alter_articles_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='rank_articles',
            new_name='ranks',
        ),
    ]
