# Generated by Django 4.0.5 on 2022-07-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_user', models.TextField(default='None')),
                ('caption_name', models.CharField(default='Название', max_length=50)),
                ('caption_mini_text', models.CharField(default='Описание', max_length=200)),
                ('duraction', models.IntegerField(default=0)),
                ('date_ex', models.TextField(default="Даты проведения в виде 'число.месяц' ")),
                ('time_ex', models.TextField(default='Время начала')),
                ('price', models.IntegerField(default=0)),
                ('place', models.IntegerField(default=0)),
            ],
        ),
    ]
