# Generated by Django 4.0.5 on 2022-07-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0002_alter_excursions_reg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursions',
            name='reg_user',
        ),
    ]
