# Generated by Django 4.0.5 on 2022-07-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excursion', '0003_remove_excursions_reg_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursion.excursions')),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
