# Generated by Django 4.0.5 on 2022-07-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0004_reg_excursion'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='Excursion_image',
            field=models.FileField(default='None', upload_to='excursion/'),
        ),
        migrations.AddField(
            model_name='excursions',
            name='rank_articles',
            field=models.CharField(choices=[('Streets', 'Streets'), ('Historical', 'Historical'), ('Buildings', 'Buildings')], default='Streets', max_length=10),
        ),
    ]
