# Generated by Django 4.0.5 on 2022-07-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0007_rename_duraction_excursions_duraction_in_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursions',
            old_name='rank_excursion',
            new_name='ranks',
        ),
    ]
