# Generated by Django 4.0.5 on 2022-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0008_rename_rank_excursion_excursions_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='registred',
            field=models.IntegerField(default=0),
        ),
    ]
