# Generated by Django 4.0.5 on 2022-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0009_excursions_registred'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_excursion',
            name='reg_date',
            field=models.TextField(default=0),
        ),
    ]
