# Generated by Django 4.0.5 on 2022-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0010_reg_excursion_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_excursion',
            name='reg_people',
            field=models.IntegerField(default=1),
        ),
    ]
